[build]
  # Directory where your source code lives (optional, default is root)
  base = "/"
  
  # Command to build your app
  command = "npm run build"
  
  # Directory to deploy (where the build outputs)
  publish = "build"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
