[build]
  base = "powerful-system"
  command = "npm ci && npm run build"
  publish = "powerful-system/dist"

[build.environment]
  NODE_VERSION = "20.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 