[build]
  command = "npm run build"
  publish = "dist"
  # Optional: set the directory of your project if not root
  # base = "/"

# Redirect all requests to index.html for SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Environment variables
#[[context.production.environment]]
#  NODE_ENV = "production"
